#! /bin/sh
#  /etc/init.d/mydaemon

NAME="enqueueData"
DESC="Enqueue Zhenhai Data"

# The path to Jsvc
EXEC="/usr/bin/jsvc"
JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64/jre/"
PROJECT_HOME="/opt/Communication"

COMMONS_DAEMON_JAR="$PROJECT_HOME/commons-daemon.jar"
PROJECT_JAR="$PROJECT_HOME/CommunicationServer-assembly-0.0.1.jar"

# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$COMMONS_DAEMON_JAR:$PROJECT_JAR"
CLASS="tw.com.zhenhai.daemon.EnQueueServerDaemon"

#The user to run the daemon as
USER="root"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/var/run/$NAME.pid"

jsvc_exec()
{  
    $EXEC -debug -home $JAVA_HOME -cp $CLASS_PATH -user $USER -pidfile $PID $1 $CLASS
    echo "$EXEC -debug -cp $CLASS_PATH -user $USER -pidfile $PID $1 $CLASS"
}

case "$1" in
    start) 
        echo "Starting the $DESC..."       
       
        # Start the service
        jsvc_exec
       
        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."
       
        # Stop the service
        jsvc_exec "-stop"      
       
        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then
           
            echo "Restarting the $DESC..."
           
            # Stop the service
            jsvc_exec "-stop"
           
            # Start the service
            jsvc_exec
           
            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
